### PR TITLE
added web component to cdm deployments

### PR DESCRIPTION
**Pull request by lee-baines**
Added web component to CDM deployment to allow default IG route to work

### CODE REVIEW

**Comment by wajihahmed** [comment]
Does this deploy ok? The s-cluster which is very tight on cpu resource.

**Comment by dgoldssfo** [comment]
Does this need to be backported to the release/6.5.0 branch? Does it require any doc changes? Also, it would be great if you could update the Helm README https://github.com/ForgeRock/forgeops/tree/master/helm with a one-liner about the new chart.

**Comment by lee-baines** [comment]
This is not a new Helm chart. I've just included it in the CDM deployment.  I'm working through the CDM cookbook with Gary to see whats been added but this has already been described as 1 of the IG examples in the documentation.  Wajih and I just agreed to not in include the web chart in the deployment, but Gary suggested that it should be in there to capture the default root successfully.

**Comment by wajihahmed** [comment]
No if it is very small then can keep it.  I was just suggesting to try the
full deployment on s-cluster if we have one to be sure.
*--*
*Wajih Ahmed* | * D*istinguished *E*ngineer | *FORGEROCK*
+1.717.379.7777 | http://gotomeet.me/wajih

**Comment by dgoldssfo** [comment]
@lee-baines OK, I see the web helm chart is in 6.5 but it's not in the README and needs to be. Not your problem though.
This change is going to affect the doc, because I will need to add it to the chapter on deploying CDM, and I'll need to change what the users sees when navigating to the IG URL.
I'll need to know if you're planning to backport it to 6.5, in which case I'll need to update the 6.5 docs.

**Pull request merged**
