### PR TITLE
Cloud 9 - cert-manager

### PR DESCRIPTION
**Pull request by lee-baines**
Added TLS certificate objects to AM/IDM/IG
Added prodTLS value
Added certificate cleanup to remove-all script

### CODE REVIEW

**Comment by lee-baines** [comment]
sure agreed. Shame they still don't support wildcard certs.  But at least this works without any additional input.

**Comment by wstrange** [comment]
What happens if just leave the TLS secrets as is, and let people delete
them if they wish

**Comment by lee-baines** [comment]
To be honest, I didn't remove the secrets initially. By keeping the TLS secret there, the certificate was only renewed on every deployment rather than a new 1 requested. Cert manager looks for the secret before requesting.

But letsencrypt have a staging area and a production area.  Production has various rate limits so I thought, for dev work, we should use their staging environment(current default behaviour).  Then customers can request production certificates using the prodTLS flag in the values file. But this then meant I needed 2 different secrets but I couldn't keep 2 different names.  So I decided to delete them everytime.

This isn't a problem if I can centralise it with the wildcard cert . I'll check that as thought it wasn't available.

**Comment by wstrange** [comment]
Lee - if we use wildcard certs, I am wondering if we need the tls.yaml file in each product directory.

AFAIK, we can have a single cert request, and then reference the same tls secret in each namespace

**Pull request merged**
