### PR TITLE
Change "base64 --decode" in schedule-backups.sh to cross platform friendly "base64 -d"

### PR DESCRIPTION
**Pull request by WillGibson**
I don't think it needs any further explanation.

### CODE REVIEW

**Comment by wstrange** [comment]
Hi Will - Thanks for the PRs - we really appreciate it!

Github is a mirror of our stash repo - so we can't take PRs here. Do you have a forgerock backstage account with stash access? If not - I can review these changes and we will see if we can get them integrated upstream

**Comment by wstrange** [comment]
Integrated upstream in stash

**Comment by WillGibson** [comment]
I have access to https://stash.forgerock.org/projects/CLOUD/repos/forgeops/browse, but i think it's read only.

What's the best way to make little contributions like this? Could you add a `CONTRIBUTING.md` maybe?

**Comment by wstrange** [comment]
Hi Will - my apologies this is so hard to contribute. I'll check with our bit bucket / stash folks to see if anything can be done.

**Comment by wstrange** [comment]
Will -If you have a ForgeRock backstage account, they tell me you should have access to stash. You can fork forgeops in stash, and create PRs.

**Comment by WillGibson** [comment]
Good to know. Thanks @wstrange.

**Comment by WillGibson** [comment]
@wstrange Do you know why thins might be? I've forked the repository and added my public SSH key to my account in stash...

```
➜ git clone ssh://git@stash.forgerock.org:7999/~willgibson/forgeops.git willgibson-forgeops-fork
Cloning into 'willgibson-forgeops-fork'...
kex_exchange_identification: read: Operation timed out
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by wstrange** [comment]
Not sure what is going on there. Can you file a ticket with the backstage
folks - they should be able to help you out

**Comment by WillGibson** [comment]
It's our VPN. blocking it :-|

**Pull request closed without merging**
